apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-11-26T15:03:26Z"
  labels:
    run: nginx
  name: nginx
  namespace: orbite-namespace  
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx    
  dnsPolicy: ClusterFirst  
  restartPolicy: Always
  